title: Darrell Mozingo's Blog
email: darrell@mozingo.net
description: >- # this means to ignore newlines until "baseurl:"
  Discussions on development principles and practices
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DarrellMozingo
github_username:  DarrellMozingo

theme: minima
plugins:
  - jekyll-feed

exclude:
   - .rbenv
   - Gemfile
   - Gemfile.lock
   - Makefile
   - README.md
